package com.ericsson.eniq.events.server.services.soap.reports.session;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "SessionPort", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface SessionPort {


    /**
     * Get Web Service Provider server info
     *
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.ServerInfo
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getServerInfo")
    @WebResult(name = "ServerInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetServerInfoResponse")
    public ServerInfo getServerInfo()
            throws DSWSException_Exception
    ;

    /**
     * Get Web Service Provider detailed server info
     *
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.ServerInfoDetails
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getServerInfoDetails")
    @WebResult(name = "ServerInfoDetails", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getServerInfoDetails", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetServerInfoDetails")
    @ResponseWrapper(localName = "getServerInfoDetailsResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetServerInfoDetailsResponse")
    public ServerInfoDetails getServerInfoDetails()
            throws DSWSException_Exception
    ;

    /**
     * Get Web Service Version
     *
     * @return returns java.lang.String
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getVersion")
    @WebResult(name = "Version", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.reports.session.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetVersionResponse")
    public String getVersion()
            throws DSWSException_Exception
    ;

    /**
     * Reset the session time out
     *
     * @param session
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/resetSessionTimeOut")
    @RequestWrapper(localName = "resetSessionTimeOut", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.ResetSessionTimeOut")
    @ResponseWrapper(localName = "resetSessionTimeOutResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.ResetSessionTimeOutResponse")
    public void resetSessionTimeOut(
            @WebParam(name = "session", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String session)
            throws DSWSException_Exception
    ;

    /**
     * Log into the Web Services
     *
     * @param credential
     * @param version
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.SessionInfo
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/login")
    @WebResult(name = "SessionInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "login", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LoginResponse")
    public SessionInfo login(
            @WebParam(name = "credential", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            Credential credential,
            @WebParam(name = "version", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String version)
            throws DSWSException_Exception
    ;

    /**
     * Log into the Web Services
     *
     * @param loginToken
     * @param reportedIPAddress
     * @param locale
     * @param timeZone
     * @param reportedHostName
     * @param version
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.SessionInfo
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/loginWithToken")
    @WebResult(name = "SessionInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "loginWithToken", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LoginWithToken")
    @ResponseWrapper(localName = "loginWithTokenResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LoginWithTokenResponse")
    public SessionInfo loginWithToken(
            @WebParam(name = "loginToken", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String loginToken,
            @WebParam(name = "locale", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String locale,
            @WebParam(name = "timeZone", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String timeZone,
            @WebParam(name = "ReportedIPAddress", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String reportedIPAddress,
            @WebParam(name = "ReportedHostName", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String reportedHostName,
            @WebParam(name = "version", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String version)
            throws DSWSException_Exception
    ;

    /**
     * Log into the Web Services with Serialized Session
     *
     * @param reportedIPAddress
     * @param locale
     * @param loginSerializedSession
     * @param timeZone
     * @param reportedHostName
     * @param version
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.SessionInfo
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/loginWithSerializedSession")
    @WebResult(name = "SessionInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "loginWithSerializedSession", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LoginWithSerializedSession")
    @ResponseWrapper(localName = "loginWithSerializedSessionResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LoginWithSerializedSessionResponse")
    public SessionInfo loginWithSerializedSession(
            @WebParam(name = "loginSerializedSession", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String loginSerializedSession,
            @WebParam(name = "locale", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String locale,
            @WebParam(name = "timeZone", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String timeZone,
            @WebParam(name = "ReportedIPAddress", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String reportedIPAddress,
            @WebParam(name = "ReportedHostName", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String reportedHostName,
            @WebParam(name = "version", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String version)
            throws DSWSException_Exception
    ;

    /**
     * Log out of the Web Services
     *
     * @param session
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.LogoutResponse")
    public void logout(
            @WebParam(name = "session", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String session)
            throws DSWSException_Exception
    ;

    /**
     * Change user password
     *
     * @param session
     * @param newPassword
     * @param oldPassword
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/changePassword")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.ChangePasswordResponse")
    public void changePassword(
            @WebParam(name = "session", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "oldPassword", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String oldPassword,
            @WebParam(name = "newPassword", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String newPassword)
            throws DSWSException_Exception
    ;

    /**
     * Get a User Dictionary Entry
     *
     * @param session
     * @param dictionary
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.session.Entry>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getDictionary")
    @WebResult(name = "Dictionary", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getDictionary", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetDictionary")
    @ResponseWrapper(localName = "getDictionaryResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetDictionaryResponse")
    public List<Entry> getDictionary(
            @WebParam(name = "session", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "dictionary", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            DictionaryType dictionary)
            throws DSWSException_Exception
    ;

    /**
     * Set a User Dictionary Entry
     *
     * @param session
     * @param entries
     * @param dictionary
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/setDictionary")
    @RequestWrapper(localName = "setDictionary", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.SetDictionary")
    @ResponseWrapper(localName = "setDictionaryResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.SetDictionaryResponse")
    public void setDictionary(
            @WebParam(name = "session", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "dictionary", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            DictionaryType dictionary,
            @WebParam(name = "entries", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            List<Entry> entries)
            throws DSWSException_Exception
    ;

    /**
     * Returns information describing the user's session
     *
     * @param sessionID
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.SessionInfo
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getSessionInfo")
    @WebResult(name = "SessionInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getSessionInfo", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetSessionInfo")
    @ResponseWrapper(localName = "getSessionInfoResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetSessionInfoResponse")
    public SessionInfo getSessionInfo(
            @WebParam(name = "sessionID", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String sessionID)
            throws DSWSException_Exception
    ;

    /**
     * Set User Preferred Locale
     *
     * @param sessionID
     * @param pvLocale
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/setPVLocale")
    @RequestWrapper(localName = "setPVLocale", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.SetPVLocale")
    @ResponseWrapper(localName = "setPVLocaleResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.SetPVLocaleResponse")
    public void setPVLocale(
            @WebParam(name = "sessionID", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String sessionID,
            @WebParam(name = "PVLocale", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
            String pvLocale)
            throws DSWSException_Exception
    ;

    /**
     * Get Supported Prefeered Locale List
     *
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.session.SupportedPVLs
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://session.dsws.businessobjects.com/2007/06/01/getSupportedPVLs")
    @WebResult(name = "SupportedPVLocales", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getSupportedPVLs", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetSupportedPVLs")
    @ResponseWrapper(localName = "getSupportedPVLsResponse", targetNamespace = "http://session.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.session.GetSupportedPVLsResponse")
    public SupportedPVLs getSupportedPVLs()
            throws DSWSException_Exception
    ;

}
