package com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "QueryAsAServiceSoap", targetNamespace = "EE_KPI_Node_Selection_Query")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface QueryAsAServiceSoap {


    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query.RunQueryAsAServiceResponse
     */
    @WebMethod(action = "EE_KPI_Node_Selection_Query/runQueryAsAService")
    @WebResult(name = "runQueryAsAServiceResponse", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
    public RunQueryAsAServiceResponse runQueryAsAService(
            @WebParam(name = "runQueryAsAService", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
            RunQueryAsAService parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EE_KPI_Node_Selection_Query", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query.RunQueryAsAServiceExResponse
     */
    @WebMethod(action = "EE_KPI_Node_Selection_Query/runQueryAsAServiceEx")
    @WebResult(name = "runQueryAsAServiceExResponse", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
    public RunQueryAsAServiceExResponse runQueryAsAServiceEx(
            @WebParam(name = "runQueryAsAServiceEx", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
            RunQueryAsAServiceEx parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EE_KPI_Node_Selection_Query", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query.ValuesOfDateResponse
     */
    @WebMethod(operationName = "valuesOf_Date", action = "EE_KPI_Node_Selection_Query/valuesOf_Date")
    @WebResult(name = "valuesOf_DateResponse", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
    public ValuesOfDateResponse valuesOfDate(
            @WebParam(name = "valuesOf_Date", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
            ValuesOfDate parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EE_KPI_Node_Selection_Query", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query.ValuesOfUCellNameResponse
     */
    @WebMethod(operationName = "valuesOf_UCell_Name", action = "EE_KPI_Node_Selection_Query/valuesOf_UCell_Name")
    @WebResult(name = "valuesOf_UCell_NameResponse", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
    public ValuesOfUCellNameResponse valuesOfUCellName(
            @WebParam(name = "valuesOf_UCell_Name", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
            ValuesOfUCellName parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EE_KPI_Node_Selection_Query", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.ee_kpi_node_selection_query.ValuesOfRNCNameResponse
     */
    @WebMethod(operationName = "valuesOf_RNC_Name", action = "EE_KPI_Node_Selection_Query/valuesOf_RNC_Name")
    @WebResult(name = "valuesOf_RNC_NameResponse", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
    public ValuesOfRNCNameResponse valuesOfRNCName(
            @WebParam(name = "valuesOf_RNC_Name", targetNamespace = "EE_KPI_Node_Selection_Query", partName = "parameters")
            ValuesOfRNCName parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EE_KPI_Node_Selection_Query", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

}
