package com.ericsson.eniq.events.server.services.soap.reports.reportengine;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * Report Engine Web Service
 * <p/>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "ReportEngine", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", wsdlLocation = "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/ReportEngine?wsdl")
public class ReportEngine
        extends Service {

    private final static URL REPORTENGINE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ericsson.eniq.events.server.services.soap.reports.reportengine.ReportEngine.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ericsson.eniq.events.server.services.soap.reports.reportengine.ReportEngine.class.getResource(".");
            url = new URL(baseUrl, "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/ReportEngine?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/ReportEngine?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REPORTENGINE_WSDL_LOCATION = url;
    }

    public ReportEngine(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportEngine() {
        super(REPORTENGINE_WSDL_LOCATION, new QName("http://reportengine.dsws.businessobjects.com/2005", "ReportEngine"));
    }

    /**
     * @return returns ReportEngineSoap
     */
    @WebEndpoint(name = "ReportEngineSoap")
    public ReportEngineSoap getReportEngineSoap() {
        return super.getPort(new QName("http://reportengine.dsws.businessobjects.com/2005", "ReportEngineSoap"), ReportEngineSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ReportEngineSoap
     */
    @WebEndpoint(name = "ReportEngineSoap")
    public ReportEngineSoap getReportEngineSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportengine.dsws.businessobjects.com/2005", "ReportEngineSoap"), ReportEngineSoap.class, features);
    }

}
