package com.ericsson.eniq.events.server.services.soap.reports.reportengine;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "ReportEngineSoap", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ReportEngineSoap {


    /**
     * Retrieve document state and output
     *
     * @param documentReference
     * @param retrieveMustFillInfo
     * @param sessionID
     * @param navigate
     * @param retrieveData
     * @param actions
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.reportengine.DocumentInformation
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://reportengine.dsws.businessobjects.com/2005/getDocumentInformation")
    @WebResult(name = "DocumentInformation", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDocumentInformation", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetDocumentInformation")
    @ResponseWrapper(localName = "getDocumentInformationResponse", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetDocumentInformationResponse")
    public DocumentInformation getDocumentInformation(
            @WebParam(name = "sessionID", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String sessionID,
            @WebParam(name = "documentReference", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "retrieveMustFillInfo", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            RetrieveMustFillInfo retrieveMustFillInfo,
            @WebParam(name = "actions", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            List<Action> actions,
            @WebParam(name = "navigate", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            Navigate navigate,
            @WebParam(name = "retrieveData", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            RetrieveData retrieveData)
            throws DSWSException_Exception
    ;

    /**
     * Retrieve images via an ImageManagement callback
     *
     * @param documentReference
     * @param sessionID
     * @param imageName
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.reportengine.Image
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://reportengine.dsws.businessobjects.com/2005/getImage")
    @WebResult(name = "Image", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetImageResponse")
    public Image getImage(
            @WebParam(name = "sessionID", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String sessionID,
            @WebParam(name = "documentReference", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "ImageName", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String imageName)
            throws DSWSException_Exception
    ;

    /**
     * Retrieve LOV of a datasource object
     *
     * @param retrieveMustFillInfo
     * @param session
     * @param dataSourceObjectKey
     * @param dataSourceUID
     * @return returns com.ericsson.eniq.events.server.services.soap.reports.reportengine.DocumentInformation
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://reportengine.dsws.businessobjects.com/2005/getDataSourceObjectLOV")
    @WebResult(name = "DocumentInformation", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDataSourceObjectLOV", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetDataSourceObjectLOV")
    @ResponseWrapper(localName = "getDataSourceObjectLOVResponse", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.reports.reportengine.GetDataSourceObjectLOVResponse")
    public DocumentInformation getDataSourceObjectLOV(
            @WebParam(name = "session", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "dataSourceUID", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String dataSourceUID,
            @WebParam(name = "dataSourceObjectKey", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            String dataSourceObjectKey,
            @WebParam(name = "retrieveMustFillInfo", targetNamespace = "http://reportengine.dsws.businessobjects.com/2005")
            RetrieveMustFillInfo retrieveMustFillInfo)
            throws DSWSException_Exception
    ;

}
