package com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "QueryAsAServiceSoap", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface QueryAsAServiceSoap {


    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery.RunQueryAsAServiceResponse
     */
    @WebMethod(action = "EniqEventsServicesNetworkRNCCellQuery/runQueryAsAService")
    @WebResult(name = "runQueryAsAServiceResponse", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
    public RunQueryAsAServiceResponse runQueryAsAService(
            @WebParam(name = "runQueryAsAService", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
            RunQueryAsAService parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery.RunQueryAsAServiceExResponse
     */
    @WebMethod(action = "EniqEventsServicesNetworkRNCCellQuery/runQueryAsAServiceEx")
    @WebResult(name = "runQueryAsAServiceExResponse", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
    public RunQueryAsAServiceExResponse runQueryAsAServiceEx(
            @WebParam(name = "runQueryAsAServiceEx", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
            RunQueryAsAServiceEx parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery.ValuesOfDateResponse
     */
    @WebMethod(operationName = "valuesOf_Date", action = "EniqEventsServicesNetworkRNCCellQuery/valuesOf_Date")
    @WebResult(name = "valuesOf_DateResponse", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
    public ValuesOfDateResponse valuesOfDate(
            @WebParam(name = "valuesOf_Date", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
            ValuesOfDate parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery.ValuesOfUCellIdResponse
     */
    @WebMethod(operationName = "valuesOf_UCell_Id", action = "EniqEventsServicesNetworkRNCCellQuery/valuesOf_UCell_Id")
    @WebResult(name = "valuesOf_UCell_IdResponse", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
    public ValuesOfUCellIdResponse valuesOfUCellId(
            @WebParam(name = "valuesOf_UCell_Id", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
            ValuesOfUCellId parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     *
     * @param requestHeader
     * @param parameters
     * @return returns com.ericsson.eniq.events.server.services.soap.network.kpi.EniqEventsServicesNetworkRNCCellQuery.ValuesOfRNCIdResponse
     */
    @WebMethod(operationName = "valuesOf_RNC_Id", action = "EniqEventsServicesNetworkRNCCellQuery/valuesOf_RNC_Id")
    @WebResult(name = "valuesOf_RNC_IdResponse", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
    public ValuesOfRNCIdResponse valuesOfRNCId(
            @WebParam(name = "valuesOf_RNC_Id", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", partName = "parameters")
            ValuesOfRNCId parameters,
            @WebParam(name = "QaaWSHeader", targetNamespace = "EniqEventsServicesNetworkRNCCellQuery", header = true, partName = "request_header")
            QaaWSHeader requestHeader);

}
