/**
* -----------------------------------------------------------------------
* COPYRIGHT Ericsson 2013 
* The copyright to the computer program(s) herein is the property of 
* Ericsson Inc. The programs may be used and/or copied only with written 
* permission from Ericsson Inc. or in accordance with the terms and 
* conditions stipulated in the agreement/contract under which the 
* program(s) have been supplied.
* -----------------------------------------------------------------------
*/
package com.ericsson.eniq.events.server.test.temptables;

public class TempTableNames {

    public static final String TEMP_DC_Z_ALARM_INFO_RAW = "#DC_Z_ALARM_INFO_RAW";

    public static final String TEMP_EVENT_E_SGEH_SUC_RAW = "#EVENT_E_SGEH_SUC_RAW";

    public static final String TEMP_EVENT_E_LTE_IMSI_RANK = "#EVENT_E_LTE_IMSI_RANK";

    public static final String TEMP_EVENT_E_SGEH_IMSI_RANK = "#EVENT_E_SGEH_IMSI_RANK";

    public static final String TEMP_EVENT_E_SGEH_ERR_RAW = "#EVENT_E_SGEH_ERR_RAW";

    public static final String TEMP_EVENT_E_SGEH_RAW = "#EVENT_E_SGEH_RAW";

    public static final String TEMP_EVENT_E_LTE_ERR_RAW = "#EVENT_E_LTE_ERR_RAW";

    public static final String TEMP_EVENT_E_LTE_SUC_RAW = "#EVENT_E_LTE_SUC_RAW";

    public static final String TEMP_EVENT_E_SGEH_IMSI_SUC_RAW="#EVENT_E_SGEH_IMSI_SUC_RAW";

    public static final String TEMP_EVENT_E_LTE_IMSI_SUC_RAW="#EVENT_E_LTE_IMSI_SUC_RAW";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_CC_SUC_15MIN = "#EVENT_E_SGEH_EVNTSRC_CC_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_CC_SUC_15MIN = "#EVENT_E_LTE_EVNTSRC_CC_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_APN_SUC_15MIN = "#EVENT_E_LTE_APN_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_APN_SUC_15MIN = "#EVENT_E_SGEH_APN_SUC_15MIN";

    public static final String TEMP_GROUP_TYPE_E_IMSI = "#GROUP_TYPE_E_IMSI";

    public static final String TEMP_GROUP_TYPE_E_TAC = "#GROUP_TYPE_E_TAC";

    public static final String TEMP_GROUP_TYPE_E_MCC_MNC = "#GROUP_TYPE_E_MCC_MNC";

    public static final String TEMP_DIM_E_SGEH_TAC = "#DIM_E_SGEH_TAC";

    public static final String TEMP_DIM_E_SGEH_RAT = "#DIM_E_SGEH_RAT";

    public static final String TEMP_DIM_E_SGEH_HIER321 = "#DIM_E_SGEH_HIER321";

    public static final String TEMP_DIM_E_SGEH_HIER321_CELL = "#DIM_E_SGEH_HIER321_CELL";

    public static final String TEMP_DIM_Z_SGEH_HIER321_CELL = "#DIM_Z_SGEH_HIER321_CELL";

    public static final String TEMP_DIM_E_RAN_HFA_CATEGORY = "#DIM_E_RAN_HFA_CATEGORY";

    public static final String TEMP_DIM_E_RAN_HFA_CAUSE_CODE_VALUE = "#DIM_E_RAN_HFA_CAUSE_CODE_VALUE";

    public static final String TEMP_DIM_Z_SGEH_HIER321 = "#DIM_Z_SGEH_HIER321";

    public static final String TEMP_GROUP_TYPE_E_APN = "#GROUP_TYPE_E_APN";

    public static final String TEMP_EVENT_E_LTE_RAW = "#EVENT_E_LTE_RAW";

    public static final String TEMP_EVENT_E_LTE_MANUF_TAC_ERR_DAY = "#EVENT_E_LTE_MANUF_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_MANUF_TAC_SUC_DAY = "#EVENT_E_LTE_MANUF_TAC_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_MANUF_TAC_SUC_15MIN = "#EVENT_E_LTE_MANUF_TAC_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_MANUF_TAC_EVENTID_ERR_DAY = "#EVENT_E_SGEH_MANUF_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_MANUF_TAC_EVENTID_SUC_DAY = "#EVENT_E_SGEH_MANUF_TAC_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_MANUF_TAC_EVENTID_ERR_DAY = "#EVENT_E_LTE_MANUF_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_MANUF_TAC_EVENTID_SUC_DAY = "#EVENT_E_LTE_MANUF_TAC_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_ERR_DAY = "#EVENT_E_LTE_VEND_HIER321_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_SUC_DAY = "#EVENT_E_LTE_VEND_HIER321_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_ERR_DAY = "#EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_DAY = "#EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_15MIN = "#EVENT_E_LTE_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_ERR_DAY = "#EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_DAY = "#EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_15MIN = "#EVENT_E_SGEH_APN_EVENTID_EVNTSRC_VEND_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_ERR_DAY = "#EVENT_E_LTE_VEND_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_SUC_DAY = "#EVENT_E_LTE_VEND_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_ERR_15MIN = "#EVENT_E_LTE_VEND_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_SUC_15MIN = "#EVENT_E_LTE_VEND_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_SUC_DAY = "#EVENT_E_SGEH_VEND_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_ERR_DAY = "#EVENT_E_SGEH_VEND_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_SUC_15MIN = "#EVENT_E_SGEH_VEND_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_ERR_15MIN = "#EVENT_E_SGEH_VEND_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_ERR_DAY = "#EVENT_E_SGEH_VEND_HIER321_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_SUC_DAY = "#EVENT_E_SGEH_VEND_HIER321_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_SUC_15MIN = "#EVENT_E_SGEH_VEND_HIER321_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_SUC_15MIN = "#EVENT_E_LTE_VEND_HIER321_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_MANUF_TAC_SUC_DAY = "#EVENT_E_SGEH_MANUF_TAC_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_MANUF_TAC_SUC_15MIN = "#EVENT_E_SGEH_MANUF_TAC_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_MANUF_TAC_ERR_DAY = "#EVENT_E_SGEH_MANUF_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_MCC_MNC_ROAM_15MIN = "#EVENT_E_SGEH_MCC_MNC_ROAM_15MIN";

    public static final String TEMP_EVENT_E_LTE_MCC_MNC_ROAM_15MIN = "#EVENT_E_LTE_MCC_MNC_ROAM_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_EVENTID_ERR_DAY = "#EVENT_E_SGEH_VEND_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_EVENTID_ERR_DAY = "#EVENT_E_LTE_VEND_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_EVENTID_SUC_DAY = "#EVENT_E_LTE_VEND_HIER321_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_EVENTID_SUC_DAY = "#EVENT_E_SGEH_VEND_HIER321_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_EVNTSRC_ERR_DAY = "#EVENT_E_LTE_APN_EVENTID_EVNTSRC_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_EVNTSRC_SUC_DAY = "#EVENT_E_LTE_APN_EVENTID_EVNTSRC_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_EVNTSRC_ERR_DAY = "#EVENT_E_SGEH_APN_EVENTID_EVNTSRC_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_EVNTSRC_SUC_DAY = "#EVENT_E_SGEH_APN_EVENTID_EVNTSRC_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_1MIN = "#EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_1MIN";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_1MIN = "#EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_1MIN";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_ERR_1MIN = "#EVENT_E_LTE_EVNTSRC_EVENTID_ERR_1MIN";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_SUC_1MIN = "#EVENT_E_LTE_EVNTSRC_EVENTID_SUC_1MIN";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_15MIN = "#EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_SGEH_APN_EVENTID_SUC_15MIN = "#EVENT_E_SGEH_APN_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_APN_EVENTID_SUC_15MIN = "#EVENT_E_LTE_APN_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_15MIN = "#EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_ERR_15MIN = "#EVENT_E_LTE_EVNTSRC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_SUC_15MIN = "#EVENT_E_LTE_EVNTSRC_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_DAY = "#EVENT_E_SGEH_EVNTSRC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_DAY = "#EVENT_E_SGEH_EVNTSRC_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_ERR_DAY = "#EVENT_E_LTE_EVNTSRC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_EVENTID_SUC_DAY = "#EVENT_E_LTE_EVNTSRC_EVENTID_SUC_DAY";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_SGEH_VEND_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER3_EVENTID_SUC_15MIN = "#EVENT_E_SGEH_VEND_HIER3_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_LTE_VEND_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER3_EVENTID_SUC_15MIN = "#EVENT_E_LTE_VEND_HIER3_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_EVENTID_ERR_15MIN = "#EVENT_E_SGEH_VEND_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_SGEH_VEND_HIER321_EVENTID_SUC_15MIN = "#EVENT_E_SGEH_VEND_HIER321_EVENTID_SUC_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_EVENTID_ERR_15MIN = "#EVENT_E_LTE_VEND_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_VEND_HIER321_EVENTID_SUC_15MIN = "#EVENT_E_LTE_VEND_HIER321_EVENTID_SUC_15MIN";

    public static final String TEMP_DIM_E_LTE_APN = "#DIM_E_LTE_APN";

    public static final String TEMP_DIM_E_SGEH_APN = "#DIM_E_SGEH_APN";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_SUC_RAW = "#EVENT_E_MSS_VOICE_CDR_SUC_RAW";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_SUC_RAW_TIMERANGE = "#EVENT_E_MSS_VOICE_CDR_SUC_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_ERR_RAW = "#EVENT_E_MSS_VOICE_CDR_ERR_RAW";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_ERR_RAW_TIMERANGE = "#EVENT_E_MSS_VOICE_CDR_ERR_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_DROP_CALL_RAW = "#EVENT_E_MSS_VOICE_CDR_DROP_CALL_RAW";

    public static final String TEMP_EVENT_E_MSS_VOICE_CDR_DROP_CALL_RAW_TIMERANGE = "#EVENT_E_MSS_VOICE_CDR_DROP_CALL_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_CDR_ERR_RAW = "#EVENT_E_MSS_LOC_SERVICE_CDR_ERR_RAW";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_CDR_ERR_RAW_TIMERANGE = "#EVENT_E_MSS_VOICE_CDR_SUC_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_CDR_SUC_RAW = "#EVENT_E_MSS_LOC_SERVICE_CDR_SUC_RAW";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_CDR_SUC_RAW_TIMERANGE = "#EVENT_E_MSS_LOC_SERVICE_CDR_SUC_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_MSS_SMS_CDR_ERR_RAW = "#EVENT_E_MSS_SMS_CDR_ERR_RAW";

    public static final String TEMP_EVENT_E_MSS_SMS_CDR_SUC_RAW = "#EVENT_E_MSS_SMS_CDR_SUC_RAW";

    public static final String TEMP_DIM_E_MSS_INTERNAL_CAUSE_CODE = "#DIM_E_MSS_INTERNAL_CAUSE_CODE";

    public static final String TEMP_DIM_E_MSS_PROTOCOL_CODE = "#DIM_E_MSS_PROTOCOL_CODE";

    public static final String TEMP_DIM_E_MSS_RANAP_CODE = "#DIM_E_MSS_RANAP_CODE";

    public static final String TEMP_DIM_E_MSS_BSSMAP_CODE = "#DIM_E_MSS_BSSMAP_CODE";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_SUC_15MIN = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_ERR_15MIN = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_SUC_DAY = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_ERR_DAY = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_EVENTID_EVNTSRC_HIER3_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_ERR_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_SUC_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_ERR_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_SUC_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER321_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_ERR_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_SUC_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_SUC_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_ERR_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_SUC_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_ERR_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_CC_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_CC_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_RANK_15MIN = "#EVENT_E_MSS_VOICE_IMSI_RANK_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_RANK_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_IMSI_RANK_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_RANK_DAY = "#EVENT_E_MSS_VOICE_IMSI_RANK_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_RANK_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_IMSI_RANK_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_LONG_DUR_RANK_15MIN = "#EVENT_E_MSS_VOICE_IMSI_LONG_DUR_RANK_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_SHORT_DUR_RANK_15MIN = "#EVENT_E_MSS_VOICE_IMSI_SHORT_DUR_RANK_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_LONG_DUR_RANK_DAY = "#EVENT_E_MSS_VOICE_IMSI_LONG_DUR_RANK_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_SHORT_DUR_RANK_DAY = "#EVENT_E_MSS_VOICE_IMSI_SHORT_DUR_RANK_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_UNANSWERED_CALL_RANK_15MIN = "#EVENT_E_MSS_VOICE_IMSI_UNANSWERED_CALL_RANK_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_IMSI_UNANSWERED_CALL_RANK_DAY = "#EVENT_E_MSS_VOICE_IMSI_UNANSWERED_CALL_RANK_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_ERR_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_SUC_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_VEND_HIER3_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_ERR_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_SUC_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_ERR_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_SUC_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_EVNTSRC_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_ERR_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_SUC_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_DROP_CALL_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_DROP_CALL_15MIN";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_ERR_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_SUC_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_VOICE_MANUF_TAC_DROP_CALL_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_DROP_CALL_DAY";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_ERR_15MIN = "#EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_SUC_15MIN = "#EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_ERR_DAY = "#EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_SUC_DAY = "#EVENT_E_MSS_LOC_SERVICE_EVENTID_EVNTSRC_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_SUC_15MIN = "#EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_SUC_15MIN";

    public static final String TEMP_EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_ERR_15MIN = "#EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_SUC_DAY = "#EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_SUC_DAY";

    public static final String TEMP_EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_ERR_DAY = "#EVENT_E_MSS_SMS_EVENTID_EVNTSRC_HIER3_ERR_DAY";

    public static final String TEMP_GROUP_TYPE_E_EVNTSRC = "#GROUP_TYPE_E_EVNTSRC";

    public static final String TEMP_DIM_E_SGEH_CAUSECODE = "#DIM_E_SGEH_CAUSECODE";

    public static final String TEMP_DIM_E_LTE_CAUSECODE = "#DIM_E_LTE_CAUSECODE";

    public static final String TEMP_DIM_E_SGEH_CC_SCC = "#TEMP_DIM_E_SGEH_CC_SCC";

    public static final String TEMP_DIM_E_LTE_CC_SCC = "#TEMP_DIM_E_LTE_CC_SCC";

    public static final String TEMP_GROUP_TYPE_E_LTE_TRAC = "#GROUP_TYPE_E_LTE_TRAC";

    public static final String TEMP_EVENT_E_LTE_EVNTSRC_CC_SCC_ERR_1MIN = "#EVENT_E_LTE_EVNTSRC_CC_SCC_ERR_1MIN";

    public static final String TEMP_EVENT_E_SGEH_EVNTSRC_CC_SCC_ERR_1MIN = "#EVENT_E_SGEH_EVNTSRC_CC_SCC_ERR_1MIN";

    public static final String TEMP_DIM_E_SGEH_SUBCAUSECODE = "#DIM_E_SGEH_SUBCAUSECODE";

    public static final String TEMP_DIM_E_LTE_SUBCAUSECODE = "#DIM_E_LTE_SUBCAUSECODE";

    public static final String TEMP_DIM_E_SGEH_CAUSE_PROT_TYPE = "#DIM_E_SGEH_CAUSE_PROT_TYPE";

    public static final String TEMP_DIM_E_LTE_CAUSE_PROT_TYPE = "#DIM_E_LTE_CAUSE_PROT_TYPE";

    public static final String TEMP_DIM_E_IMSI_MSISDN = "#DIM_E_IMSI_MSISDN";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_SUC_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_SUC_15MIN";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_ERR_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_DROP_15MIN = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_DROP_CALL_15MIN";

    public static final String TEMP_LOC_TAC_MANUF_SUM_SUC_15MIN = "#EVENT_E_MSS_LOC_SERVICE_MANUF_TAC_SUC_15MIN";

    public static final String TEMP_LOC_TAC_MANUF_SUM_ERR_15MIN = "#EVENT_E_MSS_LOC_SERVICE_MANUF_TAC_ERR_15MIN";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_SUC_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_SUC_15MIN";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_ERR_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_ERR_15MIN";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_DROP_15MIN = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_DROP_CALL_15MIN";

    public static final String TEMP_LOC_EVENT_SRC_SUM_SUC_15MIN = "#EVENT_E_MSS_LOC_SERVICE_EVNTSRC_SUC_15MIN";

    public static final String TEMP_LOC_EVENT_SRC_SUM_ERR_15MIN = "#EVENT_E_MSS_LOC_SERVICE_EVNTSRC_ERR_15MIN";

    public static final String TEMP_SMS_EVNTSRC_EVENTID_SUC_15MIN = "#EVENT_E_MSS_SMS_EVNTSRC_EVENTID_SUC_15MIN";

    public static final String TEMP_SMS_EVNTSRC_EVENTID_ERR_15MIN = "#EVENT_E_MSS_SMS_EVNTSRC_EVENTID_ERR_15MIN";

    public static final String TEMP_SMS_EVNTSRC_EVENTID_SUC_DAY = "#EVENT_E_MSS_SMS_EVNTSRC_EVENTID_SUC_DAY";

    public static final String TEMP_SMS_EVNTSRC_EVENTID_ERR_DAY = "#EVENT_E_MSS_SMS_EVNTSRC_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_SUC_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_SUC_15MIN";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_ERR_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_DROP_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_DROP_CALL_15MIN";

    public static final String TEMP_SMS_CONTROLLER_CELL_SUM_SUC_15MIN = "#EVENT_E_MSS_SMS_VEND_HIER321_EVENTID_SUC_15MIN";

    public static final String TEMP_SMS_CONTROLLER_CELL_SUM_ERR_15MIN = "#EVENT_E_MSS_SMS_VEND_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_SMS_CONTROLLER_CELL_SUM_SUC_DAY = "#EVENT_E_MSS_SMS_VEND_HIER321_EVENTID_SUC_DAY";

    public static final String TEMP_SMS_CONTROLLER_CELL_SUM_ERR_DAY = "#EVENT_E_MSS_SMS_VEND_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_LOC_CONTROLLER_CELL_SUM_SUC_15MIN = "#EVENT_E_MSS_LOC_SERVICE_VEND_HIER321_SUC_15MIN";

    public static final String TEMP_LOC_CONTROLLER_CELL_SUM_ERR_15MIN = "#EVENT_E_MSS_LOC_SERVICE_VEND_HIER321_ERR_15MIN";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_SUC_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_SUC_DAY";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_ERR_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_TAC_MANUF_SUM_DROP_DAY = "#EVENT_E_MSS_VOICE_MANUF_TAC_EVENTID_DROP_CALL_DAY";

    public static final String TEMP_LOC_TAC_MANUF_SUM_SUC_DAY = "#EVENT_E_MSS_LOC_SERVICE_MANUF_TAC_SUC_DAY";

    public static final String TEMP_LOC_TAC_MANUF_SUM_ERR_DAY = "#EVENT_E_MSS_LOC_SERVICE_MANUF_TAC_ERR_DAY";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_SUC_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_SUC_DAY";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_ERR_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_EVENT_SRC_SUM_DROP_DAY = "#EVENT_E_MSS_VOICE_EVNTSRC_EVENTID_DROP_CALL_DAY";

    public static final String TEMP_LOC_EVENT_SRC_SUM_SUC_DAY = "#EVENT_E_MSS_LOC_SERVICE_EVNTSRC_SUC_DAY";

    public static final String TEMP_LOC_EVENT_SRC_SUM_ERR_DAY = "#EVENT_E_MSS_LOC_SERVICE_EVNTSRC_ERR_DAY";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_DROP_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_DROP_CALL_15MIN";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_SUC_15MIN = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_SUC_15MIN";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_ERR_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_DROP_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_DROP_CALL_DAY";

    public static final String TEMP_VOICE_VEND_HIER3_EVENTID_SUC_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER3_EVENTID_SUC_DAY";

    public static final String TEMP_SMS_VEND_HIER3_EVENTID_SUC_15MIN = "#EVENT_E_MSS_SMS_VEND_HIER3_EVENTID_SUC_15MIN";

    public static final String TEMP_SMS_VEND_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_MSS_SMS_VEND_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_SMS_VEND_HIER3_EVENTID_SUC_DAY = "#EVENT_E_MSS_SMS_VEND_HIER3_EVENTID_SUC_DAY";

    public static final String TEMP_SMS_VEND_HIER3_EVENTID_ERR_DAY = "#EVENT_E_MSS_SMS_VEND_HIER3_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_SUC_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_SUC_DAY";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_ERR_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_VOICE_CONTROLLER_CELL_SUM_DROP_DAY = "#EVENT_E_MSS_VOICE_VEND_HIER321_EVENTID_DROP_CALL_DAY";

    public static final String TEMP_LOC_CONTROLLER_CELL_SUM_SUC_DAY = "#EVENT_E_MSS_LOC_SERVICE_VEND_HIER321_SUC_DAY";

    public static final String TEMP_LOC_CONTROLLER_CELL_SUM_ERR_DAY = "#EVENT_E_MSS_LOC_SERVICE_VEND_HIER321_ERR_DAY";

    public static final String TEMP_DIM_E_MSS_FAULT_CODE = "#DIM_E_MSS_FAULT_CODE";

    public static final String TEMP_DIM_E_MSS_EVNTSRC = "#DIM_E_MSS_EVNTSRC";

    public static final String TEMP_DIM_E_MSS_EVENTTYPE = "#DIM_E_MSS_EVENTTYPE";

    public static final String TEMP_DIM_E_MSS_LCS_CLIENT_TYPE = "#DIM_E_MSS_LCS_CLIENT_TYPE";

    public static final String TEMP_DIM_E_MSS_TYPE_LOCATION_REQ = "#DIM_E_MSS_TYPE_LOCATION_REQ";

    public static final String TEMP_DIM_E_MSS_UNSUC_POSITION_REASON = "#DIM_E_MSS_UNSUC_POSITION_REASON";

    public static final String TEMP_GROUP_TYPE_E_EVNTSRC_CS = "#GROUP_TYPE_E_EVNTSRC_CS";

    public static final String TEMP_GROUP_TYPE_E_RAT_VEND_HIER3 = "#GROUP_TYPE_E_RAT_VEND_HIER3";

    public static final String TEMP_GROUP_TYPE_E_RAT_VEND_HIER321 = "#GROUP_TYPE_E_RAT_VEND_HIER321";

    public static final String TEMP_EVENT_E_GSN_DT_SGSN_DAY = "#EVENT_E_GSN_DT_SGSN_DAY";

    public static final String TEMP_EVENT_E_GSN_DTPDP_SGSN_DAY = "#EVENT_E_GSN_DTPDP_SGSN_DAY";

    public static final String TEMP_EVENT_E_GSN_DT_APN_DAY = "#EVENT_E_GSN_DT_APN_DAY";

    public static final String TEMP_EVENT_E_GSN_DTPDP_APN_DAY = "#EVENT_E_GSN_DTPDP_APN_DAY";

    public static final String TEMP_EVENT_E_GSN_DT_NETWORK_DAY = "#EVENT_E_GSN_DT_NETWORK_DAY";

    public static final String TEMP_EVENT_E_GSN_DTPDP_NETWORK_DAY = "#EVENT_E_GSN_DTPDP_NETWORK_DAY";

    public static final String TEMP_EVENT_E_GSN_DT_RAW = "#EVENT_E_GSN_DT_RAW";

    public static final String TEMP_EVENT_E_GSN_DTPDP_RAW = "#EVENT_E_GSN_DTPDP_RAW";

    public static final String TEMP_EVENT_E_GSN_DT_TERM_DAY = "#EVENT_E_GSN_DT_TERM_DAY";

    public static final String TEMP_EVENT_E_GSN_DTPDP_TERM_DAY = "#EVENT_E_GSN_DTPDP_TERM_DAY";

    public static final String TEMP_DIM_E_SGEH_MCCMNC = "#DIM_E_SGEH_MCCMNC";

    public static final String TEMP_DIM_E_MSS_MSG_TYPE_INDICATOR = "#DIM_E_MSS_MSG_TYPE_INDICATOR";

    public static final String TEMP_DIM_E_MSS_SMS_RESULT = "#DIM_E_MSS_SMS_RESULT";

    public static final String TEMP_EVENT_E_LTE_ERR_RAW_TIMERANGE = "#EVENT_E_LTE_ERR_RAW_TIMERANGE";

    public static final String TEMP_VERSIONING = "#VERSIONING";

    public static final String TEMP_EVENT_E_RAN_CFA_RAW = "#EVENT_E_RAN_CFA_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_CFA_TAC_ERR_DAY = "#EVENT_E_RAN_CFA_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_CFA_TAC_EVENTID_ERR_DAY = "#EVENT_E_RAN_CFA_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_CFA_TAC_EVENTID_ERR_15MIN = "#EVENT_E_RAN_CFA_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_DIM_E_RAN_RNC = "#DIM_E_RAN_RNC";

    public static final String TEMP_DIM_E_RAN_RNCFUNCTION = "#DIM_E_RAN_RNCFUNCTION";

    public static final String TEMP_EVENT_E_GSN_DTPDP_RAW_TIMERANGE = "#EVENT_E_GSN_DTPDP_RAW_TIMERANGE";

    public static final String TEMP_EVENT_E_GSN_DT_RAW_TIMERANGE = "#EVENT_E_GSN_DT_RAW_TIMERANGE";

    public static final String TEMP_DIM_E_LTE_EVENTTYPE = "#DIM_E_LTE_EVENTTYPE";

    public static final String TEMP_DIM_E_SGEH_EVENTTYPE = "#DIM_E_SGEH_EVENTTYPE";

    public static final String TEMP_DIM_E_SGEH_EVENTRESULT = "#DIM_E_SGEH_EVENTRESULT";

    public static final String TEMP_DIM_E_LTE_ATTACHTYPE = "#DIM_E_LTE_ATTACHTYPE";

    public static final String TEMP_EVENT_E_RAN_CFA_VEND_HIER3_15MIN = "#EVENT_E_RAN_CFA_VEND_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_EVENTID_CV_ECV_ERR_15MIN = "#EVENT_E_RAN_CFA_HIER3_EVENTID_CV_ECV_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_EVENTID_CV_ECV_ERR_DAY = "#EVENT_E_RAN_CFA_HIER3_EVENTID_CV_ECV_ERR_DAY";

    public static final String TEMP_DIM_E_RAN_CFA_EVENTTYPE = "#DIM_E_RAN_CFA_EVENTTYPE";

    public static final String TEMP_EVENT_E_RAN_CFA_VEND_HIER3_EVENTID_15MIN = "#EVENT_E_RAN_CFA_VEND_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_DIM_E_RAN_CFA_PROCEDURE_INDICATOR = "#DIM_E_RAN_CFA_PROCEDURE_INDICATOR";

    public static final String TEMP_DIM_E_RAN_CFA_EVALUATION_CASE = "#DIM_E_RAN_CFA_EVALUATION_CASE";

    public static final String TEMP_DIM_E_RAN_CFA_EXCEPTION_CLASS = "#DIM_E_RAN_CFA_EXCEPTION_CLASS";

    public static final String TEMP_DIM_E_RAN_CFA_CAUSE_VALUE = "#DIM_E_RAN_CFA_CAUSE_VALUE";

    public static final String TEMP_DIM_E_RAN_CFA_EXTENDED_CAUSE_VALUE = "#DIM_E_RAN_CFA_EXTENDED_CAUSE_VALUE";

    public static final String TEMP_DIM_E_RAN_CFA_SEVERITY_INDICATOR = "#DIM_E_RAN_CFA_SEVERITY_INDICATOR";

    public static final String TEMP_EVENT_E_RAN_CFA_MANUF_TAC_EVENTID_15MIN = "#EVENT_E_RAN_CFA_MANUF_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_TAC_EVENTID_DAY = "#EVENT_E_RAN_CFA_TAC_EVENTID_ERR_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_TAC_EVENTID_15MIN = "#EVENT_E_RAN_CFA_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_15MIN = "#EVENT_E_RAN_CFA_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_DAY = "#EVENT_E_RAN_CFA_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_EVENTID_DAY = "#EVENT_E_RAN_CFA_HIER3_EVENTID_ERR_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_EVENTID_15MIN = "#EVENT_E_RAN_CFA_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_IMSI_RANK_DAY = "#EVENT_E_RAN_CFA_IMSI_RANK_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ERR_RAW = "#EVENT_E_LTE_CFA_ERR_RAW";

    public static final String TEMP_EVENT_E_LTE_HFA_ERR_RAW = "#EVENT_E_LTE_HFA_ERR_RAW";

    public static final String TEMP_EVENT_E_LTE_CFA_IMSI_RANK_15MIN = "#EVENT_E_LTE_CFA_IMSI_RANK_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_IMSI_RANK_DAY = "#EVENT_E_LTE_CFA_IMSI_RANK_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_TAC_EVENTID_ERR_15MIN = "#EVENT_E_LTE_CFA_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_TAC_EVENTID_ERR_DAY = "#EVENT_E_LTE_CFA_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_TRAC_HIER3_ERR_15MIN = "#EVENT_E_LTE_CFA_TRAC_HIER3_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_TRAC_HIER3_ERR_DAY = "#EVENT_E_LTE_CFA_TRAC_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_TRAC_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_LTE_CFA_TRAC_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_TRAC_HIER3_EVENTID_ERR_DAY = "#EVENT_E_LTE_CFA_TRAC_HIER3_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER3_CC_ERR_15MIN = "#EVENT_E_LTE_CFA_HIER3_CC_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER3_CC_ERR_DAY = "#EVENT_E_LTE_CFA_HIER3_CC_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER321_EVENTID_ERR_15MIN = "#EVENT_E_LTE_CFA_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER321_EVENTID_ERR_DAY = "#EVENT_E_LTE_CFA_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_ERR_RAW = "#EVENT_E_GSM_CFA_ERR_RAW";

    public static final String TEMP_EVENT_E_GSM_CFA_SUC_RAW = "#EVENT_E_GSM_CFA_SUC_RAW";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER321_ERR_DAY = "#EVENT_E_GSM_CFA_HIER321_ERR_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER321_SUC_DAY = "#EVENT_E_GSM_CFA_HIER321_SUC_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_UC_ERR_DAY = "#EVENT_E_GSM_CFA_HIER3_UC_ERR_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_ERR_DAY = "#EVENT_E_GSM_CFA_HIER3_CG_ERR_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_SUC_DAY = "#EVENT_E_GSM_CFA_HIER3_CG_SUC_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_UC_EC_ERR_15MIN = "#EVENT_E_GSM_CFA_HIER3_UC_EC_ERR_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_EC_ERR_15MIN = "#EVENT_E_GSM_CFA_HIER3_CG_EC_ERR_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_EC_SUC_15MIN = "#EVENT_E_GSM_CFA_HIER3_CG_EC_SUC_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_UC_ERR_15MIN = "#EVENT_E_GSM_CFA_HIER3_UC_ERR_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_ERR_15MIN = "#EVENT_E_GSM_CFA_HIER3_CG_ERR_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_HIER3_CG_SUC_15MIN = "#EVENT_E_GSM_CFA_HIER3_CG_SUC_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_TAC_CG_EC_ERR_15MIN = "#EVENT_E_GSM_CFA_TAC_CG_EC_ERR_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_TAC_ERR_DAY = "#EVENT_E_GSM_CFA_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_TAC_SUC_DAY = "#EVENT_E_GSM_CFA_TAC_SUC_DAY";

    public static final String TEMP_DIM_E_GSM_CFA_URGENCY_CONDITION = "#DIM_E_GSM_CFA_URGENCY_CONDITION";

    public static final String TEMP_GROUP_TYPE_E_IMSI_RAW = "#GROUP_TYPE_E_IMSI_RAW";

    public static final String TEMP_DIM_E_LTE_HIER321 = "#DIM_E_LTE_HIER321";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_ERR_RAW = "#EVENT_E_LTE_CFA_ARRAY_ERAB_ERR_RAW";

    public static final String TEMP_EVENT_E_LTE_HFA_ARRAY_ERAB_ERR_RAW = "#EVENT_E_LTE_HFA_ARRAY_ERAB_ERR_RAW";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_PCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_PCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_PCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_PCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_QCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_QCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_QCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_TRAC_HIER3_EVENTID_QCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_PCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_PCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_PCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_PCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_PCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_PCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_PCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_PCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_15MIN = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_DAY = "#EVENT_E_LTE_CFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_DAY";

    public static final String TEMP_DIM_E_LTE_CFA_EVENTTYPE = "#DIM_E_LTE_CFA_EVENTTYPE";

    public static final String TEMP_DIM_E_LTE_CFA_GUMMEI_TYPE = "#DIM_E_LTE_CFA_GUMMEI_TYPE";

    public static final String TEMP_DIM_E_LTE_CFA_TTI_BUNDLING_MODE = "#DIM_E_LTE_CFA_TTI_BUNDLING_MODE";

    public static final String TEMP_DIM_E_LTE_HFA_EVENTTYPE = "#DIM_E_LTE_HFA_EVENTTYPE";

    public static final String TEMP_DIM_E_LTE_HFA_CAUSE_CODE = "#DIM_E_LTE_HFA_CAUSE_CODE";

    public static final String TEMP_DIM_E_LTE_QCI = "#DIM_E_LTE_QCI";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_RESULT = "#DIM_E_LTE_CFA_ERAB_SETUP_RESULT";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_REQ_PCI = "#DIM_E_LTE_CFA_ERAB_SETUP_REQ_PCI";

    public static final String TEMP_DIM_E_LTE_HFA_ERAB_SETUP_REQ_PCI = "#DIM_E_LTE_HFA_ERAB_SETUP_REQ_PCI";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_REQ_PVI = "#DIM_E_LTE_CFA_ERAB_SETUP_REQ_PVI";

    public static final String TEMP_DIM_E_LTE_HFA_ERAB_SETUP_REQ_PVI = "#DIM_E_LTE_HFA_ERAB_SETUP_REQ_PVI";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_ATT_ACC_TYPE = "#DIM_E_LTE_CFA_ERAB_SETUP_ATT_ACC_TYPE";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_FAIL_3GPP_CAUSE_GROUP = "#DIM_E_LTE_CFA_ERAB_SETUP_FAIL_3GPP_CAUSE_GROUP";

    public static final String TEMP_DIM_E_LTE_CFA_ERAB_SETUP_SUCC_ACC_TYPE = "#DIM_E_LTE_CFA_ERAB_SETUP_SUCC_ACC_TYPE";

    public static final String TEMP_DIM_E_LTE_CFA_CAUSE_CODE = "#DIM_E_LTE_CFA_CAUSE_CODE";

    public static final String TEMP_DIM_E_LTE_CFA_INTERNAL_RELEASE_CAUSE = "#DIM_E_LTE_CFA_INTERNAL_RELEASE_CAUSE";

    public static final String TEMP_DIM_E_LTE_CFA_RRC_ESTABL_CAUSE = "#DIM_E_LTE_CFA_RRC_ESTABL_CAUSE";

    public static final String TEMP_DIM_E_LTE_CFA_TRIGGERING_NODE = "#DIM_E_LTE_CFA_TRIGGERING_NODE";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_LTE_CFA_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER3_EVENTID_ERR_15MIN = "#EVENT_E_LTE_HFA_HIER3_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_CFA_HIER3_EVENTID_ERR_DAY = "#EVENT_E_LTE_CFA_HIER3_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER3_EVENTID_ERR_DAY = "#EVENT_E_LTE_HFA_HIER3_EVENTID_ERR_DAY";

    public static final String TEMP_DIM_E_GSM_CFA_EVENTTYPE = "#DIM_E_GSM_CFA_EVENTTYPE";

    public static final String TEMP_DIM_E_GSM_CFA_EXTENDED_CAUSE = "#DIM_E_GSM_CFA_EXTENDED_CAUSE";

    public static final String TEMP_DIM_E_GSM_CFA_AF_CAUSE = "#DIM_E_GSM_CFA_AF_CAUSE";

    public static final String TEMP_DIM_E_GSM_CFA_RELEASE_TYPE = "#DIM_E_GSM_CFA_RELEASE_TYPE";

    public static final String TEMP_DIM_E_GSM_CFA_VAMOS_NEIGHBOR_INDICATOR = "#DIM_E_GSM_CFA_VAMOS_NEIGHBOR_INDICATOR";

    public static final String TEMP_DIM_E_GSM_CFA_RSAI = "#DIM_E_GSM_CFA_RSAI";

    public static final String TEMP_DIM_E_GSM_CFA_CHANNEL_TYPE = "#DIM_E_GSM_CFA_CHANNEL_TYPE";

    public static final String TEMP_DIM_E_GSM_CFA_CAUSE_GROUP = "#DIM_E_GSM_CFA_CAUSE_GROUP";

    public static final String TEMP_EVENT_E_GSM_CFA_IMSI_RANK_DAY = "#EVENT_E_GSM_CFA_IMSI_RANK_DAY";

    public static final String TEMP_EVENT_E_GSM_PS_ERR_RAW = "#EVENT_E_GSM_PS_ERR_RAW";

    public static final String TEMP_EVENT_E_GSM_PS_ALL_RAW = "#EVENT_E_GSM_PS_ALL_RAW";

    public static final String TEMP_EVENT_E_GSM_PS_ALL_HIER3_DAY = "#EVENT_E_GSM_PS_ALL_HIER3_DAY";

    public static final String TEMP_EVENT_E_GSM_PS_ALL_HIER321_DAY = "#EVENT_E_GSM_PS_ALL_HIER321_DAY";

    public static final String TEMP_EVENT_E_GSM_PS_ALL_IMSI_RANK_DAY = "#EVENT_E_GSM_PS_ALL_IMSI_RANK_DAY";

    public static final String TEMP_DIM_E_GSM_PS_TBF_RELEASE_CAUSE = "#DIM_E_GSM_PS_TBF_RELEASE_CAUSE";

    public static final String TEMP_DIM_E_GSM_PS_TBF_MUX = "#DIM_E_GSM_PS_TBF_MUX";

    public static final String TEMP_DIM_E_GSM_PS_DATA_VALID_INDICATOR = "#DIM_E_GSM_PS_DATA_VALID_INDICATOR";

    public static final String TEMP_DIM_E_GSM_PS_MS_SAIC_CAP = "#DIM_E_GSM_PS_MS_SAIC_CAP";

    public static final String TEMP_DIM_E_GSM_PS_AQM_ACTIVE = "#DIM_E_GSM_PS_AQM_ACTIVE";

    public static final String TEMP_DIM_E_GSM_PS_DTM_FLAG = "#DIM_E_GSM_PS_DTM_FLAG";

    public static final String TEMP_DIM_E_GSM_PS_RLC_MODE = "#DIM_E_GSM_PS_RLC_MODE";

    public static final String TEMP_DIM_E_GSM_PS_DIR = "#DIM_E_GSM_PS_DIR";

    public static final String TEMP_DIM_E_GSM_PS_OFLW = "#DIM_E_GSM_PS_OFLW";

    public static final String TEMP_DIM_E_GSM_PS_MS_3GPP_CAP = "#DIM_E_GSM_PS_MS_3GPP_CAP";

    public static final String TEMP_DIM_E_GSM_PS_TTI_MODE = "#DIM_E_GSM_PS_TTI_MODE";

    public static final String TEMP_DIM_E_GSM_PS_REDUCED_LATENCY = "#DIM_E_GSM_PS_REDUCED_LATENCY";

    public static final String TEMP_DIM_E_GSM_PS_GPRS_MEAS_REPORT_RXQUAL_DL = "#DIM_E_GSM_PS_GPRS_MEAS_REPORT_RXQUAL_DL";

    public static final String TEMP_DIM_E_GSM_PS_GPRS_MEAS_REPORT_SIGN_VAR = "#DIM_E_GSM_PS_GPRS_MEAS_REPORT_SIGN_VAR";

    public static final String TEMP_DIM_E_GSM_PS_GPRS_MEAS_REPORT_MEAN_BEP = "#DIM_E_GSM_PS_GPRS_MEAS_REPORT_MEAN_BEP";

    public static final String TEMP_DIM_E_GSM_PS_GPRS_MEAS_REPORT_CV_BEP = "#DIM_E_GSM_PS_GPRS_MEAS_REPORT_CV_BEP";

    public static final String TEMP_DIM_E_GSM_PS_GPRS_MEAS_REPORT_CVALUE = "#DIM_E_GSM_PS_GPRS_MEAS_REPORT_CVALUE";

    public static final String TEMP_DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_850 = "#DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_850";

    public static final String TEMP_DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_900 = "#DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_900";

    public static final String TEMP_DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_1800 = "#DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_1800";

    public static final String TEMP_DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_1900 = "#DIM_E_GSM_PS_MS_FREQ_BAND_CAP_GSM_1900";

    public static final String TEMP_DIM_E_GSM_PS_PAN_INDICATOR = "#DIM_E_GSM_PS_PAN_INDICATOR";

    public static final String TEMP_DIM_E_GSM_PS_TBF_MODE = "#DIM_E_GSM_PS_TBF_MODE";

    public static final String TEMP_DIM_E_GSM_PS_CHANNEL_RELATED_RELEASE_CAUSE_GROUP = "#DIM_E_GSM_PS_CHANNEL_RELATED_RELEASE_CAUSE_GROUP";

    public static final String TEMP_DIM_E_GSM_PS_DCDL_CAPABILITY = "#DIM_E_GSM_PS_DCDL_CAPABILITY";

    public static final String TEMP_DIM_E_GSM_PS_DCDL_INDICATOR = "#DIM_E_GSM_PS_DCDL_INDICATOR";

    public static final String TEMP_DIM_E_GSM_PS_MS_MSLOT_CAP_REDUCTION = "#DIM_E_GSM_PS_MS_MSLOT_CAP_REDUCTION";

    public static final String TEMP_DIM_E_GSM_PS_EVENTTYPE = "#DIM_E_GSM_PS_EVENTTYPE";

    public static final String TEMP_EVENT_E_RAN_CFA_CELL_ID_EVENTID = "#EVENT_E_RAN_CFA_HIER3_CELL_ID_EVENTID_ERR_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_CELL_ID_EVENTID_15MIN = "#EVENT_E_RAN_CFA_HIER3_CELL_ID_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_CELL_ID_DAY = "#EVENT_E_RAN_CFA_HIER3_CELL_ID_ERR_DAY";

    public static final String EVENT_E_RAN_CFA_TAC_15MIN = "#EVENT_E_RAN_CFA_TAC_ERR_15MIN";

    public static final String EVENT_E_RAN_CFA_TAC_DAY = "#EVENT_E_RAN_CFA_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_ERR_RAW = "#EVENT_E_RAN_HFA_SOHO_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_ERR_RAW = "#EVENT_E_RAN_HFA_HSDSCH_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_ERR_RAW = "#EVENT_E_RAN_HFA_IFHO_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_ERR_RAW = "#EVENT_E_RAN_HFA_IRAT_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_TAC_ERR_DAY = "#EVENT_E_RAN_HFA_SOHO_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_TAC_ERR_DAY = "#EVENT_E_RAN_HFA_HSDSCH_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_TAC_ERR_DAY = "#EVENT_E_RAN_HFA_IFHO_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_TAC_ERR_DAY = "#EVENT_E_RAN_HFA_IRAT_TAC_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_CFA_ERR_RAW = "#EVENT_E_RAN_CFA_ERR_RAW";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_CV_SCV_DAY = "#EVENT_E_RAN_HFA_SOHO_CV_SCV_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_CV_SCV_DAY = "#EVENT_E_RAN_HFA_IFHO_CV_SCV_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_CV_SCV_DAY = "#EVENT_E_RAN_HFA_IRAT_CV_SCV_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_CV_SCV_DAY = "#EVENT_E_RAN_HFA_HSDSCH_CV_SCV_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_HIER3_ERR_DAY = "#EVENT_E_RAN_HFA_SOHO_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_HIER3_ERR_DAY = "#EVENT_E_RAN_HFA_IFHO_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_HIER3_ERR_DAY = "#EVENT_E_RAN_HFA_IRAT_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_HIER3_ERR_DAY = "#EVENT_E_RAN_HFA_HSDSCH_HIER3_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_HIER3_CELL_ERR_DAY = "#EVENT_E_RAN_HFA_SOHO_HIER3_CELL_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_HIER3_CELL_ERR_DAY = "#EVENT_E_RAN_HFA_IFHO_HIER3_CELL_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_HIER3_CELL_ERR_DAY = "#EVENT_E_RAN_HFA_IRAT_HIER3_CELL_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_HIER3_CELL_ERR_DAY = "#EVENT_E_RAN_HFA_HSDSCH_HIER3_CELL_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_IMSI_ERR_15MIN = "#EVENT_E_RAN_HFA_SOHO_IMSI_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_HFA_SOHO_IMSI_ERR_DAY = "#EVENT_E_RAN_HFA_SOHO_IMSI_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_IMSI_ERR_15MIN = "#EVENT_E_RAN_HFA_IFHO_IMSI_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_HFA_IFHO_IMSI_ERR_DAY = "#EVENT_E_RAN_HFA_IFHO_IMSI_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_IMSI_ERR_15MIN = "#EVENT_E_RAN_HFA_IRAT_IMSI_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_HFA_IRAT_IMSI_ERR_DAY = "#EVENT_E_RAN_HFA_IRAT_IMSI_ERR_DAY";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_IMSI_ERR_15MIN = "#EVENT_E_RAN_HFA_HSDSCH_IMSI_ERR_15MIN";

    public static final String TEMP_EVENT_E_RAN_HFA_HSDSCH_IMSI_ERR_DAY = "#EVENT_E_RAN_HFA_HSDSCH_IMSI_ERR_DAY";

    public static final String TEMP_DIM_E_RAN_HFA_SUB_CAUSE_CODE_VALUE = "#DIM_E_RAN_HFA_SUB_CAUSE_CODE_VALUE";

    public static final String TEMP_EVENT_E_RAN_CFA_MCC_MNC_ROAM_DAY = "#EVENT_E_RAN_CFA_MCC_MNC_ROAM_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_MCC_MNC_ROAM_DAY = "#EVENT_E_GSM_CFA_MCC_MNC_ROAM_DAY";

    public static final String TEMP_EVENT_E_GSM_CFA_MCC_MNC_ROAM_15MIN = "#EVENT_E_GSM_CFA_MCC_MNC_ROAM_15MIN";

    public static final String TEMP_EVENT_E_GSM_CFA_MCC_MNC_ROAM_SUC_15MIN = "#EVENT_E_GSM_CFA_MCC_MNC_ROAM_SUC_15MIN";

    public static final String TEMP_GROUP_TYPE_E_RAT_VEND_HIER321_CELL = "#GROUP_TYPE_E_RAT_VEND_HIER321_CELL";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER321_EVENTID_ERR_15MIN = "#EVENT_E_LTE_HFA_HIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER321_EVENTID_ERR_DAY = "#EVENT_E_LTE_HFA_HIER321_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_THIER321_EVENTID_ERR_15MIN = "#EVENT_E_LTE_HFA_THIER321_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_THIER321_EVENTID_ERR_DAY = "#EVENT_E_LTE_HFA_THIER321_EVENTID_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER3_CC_ERR_15MIN = "#EVENT_E_LTE_HFA_HIER3_CC_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_HIER3_CC_ERR_DAY = "#EVENT_E_LTE_HFA_HIER3_CC_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_15MIN = "#EVENT_E_LTE_HFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_DAY = "#EVENT_E_LTE_HFA_ARRAY_ERAB_HIER3_EVENTID_QCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_15MIN = "#EVENT_E_LTE_HFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_DAY = "#EVENT_E_LTE_HFA_ARRAY_ERAB_HIER321_EVENTID_QCI_ERR_DAY";

    public static final String TEMP_EVENT_E_LTE_HFA_TAC_EVENTID_ERR_15MIN = "#EVENT_E_LTE_HFA_TAC_EVENTID_ERR_15MIN";

    public static final String TEMP_EVENT_E_LTE_HFA_TAC_EVENTID_ERR_DAY = "#EVENT_E_LTE_HFA_TAC_EVENTID_ERR_DAY";

    public static final String TEMP_DIM_E_RAN_CFA_DISCONNECTION = "#DIM_E_RAN_CFA_DISCONNECTION";

    public static final String TEMP_DIM_E_RAN_CFA_RRC_ESTABLISHMENT_CAUSE = "#DIM_E_RAN_CFA_RRC_ESTABLISHMENT_CAUSE";

    public static final String TEMP_DIM_E_RAN_CFA_TRIGGER_POINT = "#DIM_E_RAN_CFA_TRIGGER_POINT";

    public static final String TEMP_DIM_E_RAN_HFA_EVENTTYPE = "#DIM_E_RAN_HFA_EVENTTYPE";

    public static final String TEMP_DIM_E_RAN_RABTYPE = "#DIM_E_RAN_RABTYPE";

    public static final String TEMP_DIM_E_RAN_CFA_UTRAN_RANAP_CAUSE = "#DIM_E_RAN_CFA_UTRAN_RANAP_CAUSE";

    public static final String TEMP_DIM_E_RAN_CFA_CN_RANAP_CAUSE = "#DIM_E_RAN_CFA_CN_RANAP_CAUSE";

    public static final String TEMP_DIM_E_RAN_ULINT_MAPPING = "#DIM_E_RAN_ULINT_MAPPING";

    public static final String TEMP_DIM_E_RAN_RSCP_MAPPING = "#DIM_E_RAN_RSCP_MAPPING";

    public static final String TEMP_DIM_E_RAN_ECNO_MAPPING = "#DIM_E_RAN_ECNO_MAPPING";
    
    public static final String TEMP_EVENT_E_RAN_CFA_TAC_ALLCALLS_15MIN = "#EVENT_E_RAN_CFA_TAC_ALLCALLS_15MIN";
    
    public static final String TEMP_EVENT_E_RAN_CFA_TAC_ALLCALLS_DAY = "#EVENT_E_RAN_CFA_TAC_ALLCALLS_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_ALLCALLS_15MIN = "#EVENT_E_RAN_CFA_HIER3_ALLCALLS_15MIN";
    
    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_ALLCALLS_DAY = "#EVENT_E_RAN_CFA_HIER3_ALLCALLS_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_CELL_ID_ALLCALLS_DAY = "#EVENT_E_RAN_CFA_HIER3_CELL_ID_ALLCALLS_DAY";
    
    public static final String TEMP_EVENT_E_RAN_CFA_HIER3_CELL_ID_ALLCALLS_15MIN = "#EVENT_E_RAN_CFA_HIER3_CELL_ID_ALLCALLS_15MIN";
}
