
package com.ericsson.eniq.events.server.services.soap.network.kpi.rrc_conn_succ_rate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
// Suppress PMD warnings as it's a generated class
@SuppressWarnings("PMD")
@WebService(name = "QueryAsAServiceSoap", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryAsAServiceSoap {


    /**
     * Get Web Service Provider server info
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns com.ericsson.eniq.events.server.services.soap.network.kpi.rrc_conn_succ_rate.RunQueryAsAServiceResponse
     */
    @WebMethod(action = "ENIQ_Events_Rrc_Conn_Succ_Rate/runQueryAsAService")
    @WebResult(name = "runQueryAsAServiceResponse", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
    public RunQueryAsAServiceResponse runQueryAsAService(
        @WebParam(name = "runQueryAsAService", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
        RunQueryAsAService parameters,
        @WebParam(name = "QaaWSHeader", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", header = true, partName = "request_header")
        QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns com.ericsson.eniq.events.server.services.soap.network.kpi.rrc_conn_succ_rate.RunQueryAsAServiceExResponse
     */
    @WebMethod(action = "ENIQ_Events_Rrc_Conn_Succ_Rate/runQueryAsAServiceEx")
    @WebResult(name = "runQueryAsAServiceExResponse", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
    public RunQueryAsAServiceExResponse runQueryAsAServiceEx(
        @WebParam(name = "runQueryAsAServiceEx", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
        RunQueryAsAServiceEx parameters,
        @WebParam(name = "QaaWSHeader", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", header = true, partName = "request_header")
        QaaWSHeader requestHeader);

    /**
     * Get Web Service Provider server info
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns com.ericsson.eniq.events.server.services.soap.network.kpi.rrc_conn_succ_rate.ValuesOfDateResponse
     */
    @WebMethod(operationName = "valuesOf_Date", action = "ENIQ_Events_Rrc_Conn_Succ_Rate/valuesOf_Date")
    @WebResult(name = "valuesOf_DateResponse", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
    public ValuesOfDateResponse valuesOfDate(
        @WebParam(name = "valuesOf_Date", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", partName = "parameters")
        ValuesOfDate parameters,
        @WebParam(name = "QaaWSHeader", targetNamespace = "ENIQ_Events_Rrc_Conn_Succ_Rate", header = true, partName = "request_header")
        QaaWSHeader requestHeader);

}
