package com.ericsson.eniq.events.server.services.soap.queryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "QueryService", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface QueryService {


    /**
     * @param session
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.queryservice.DataSource>
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/getDataSourceList")
    @WebResult(name = "dataSource", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDataSourceList", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataSourceList")
    @ResponseWrapper(localName = "getDataSourceListResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataSourceListResponse")
    public List<DataSource> getDataSourceList(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session)
            throws DSWSException_Exception
    ;

    /**
     * @param session
     * @param dataSourceUID
     * @return returns com.ericsson.eniq.events.server.services.soap.queryservice.DataSourceSpecification
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/getDataSource")
    @WebResult(name = "dataSourceSpecification", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDataSource", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataSource")
    @ResponseWrapper(localName = "getDataSourceResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataSourceResponse")
    public DataSourceSpecification getDataSource(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "dataSourceUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataSourceUID)
            throws DSWSException_Exception
    ;

    /**
     * @param documentReference
     * @param session
     * @param includeQuerySpecification
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.queryservice.DataProviderInformation>
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/getDataProviderList")
    @WebResult(name = "dataProviderInformation", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDataProviderList", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataProviderList")
    @ResponseWrapper(localName = "getDataProviderListResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataProviderListResponse")
    public List<DataProviderInformation> getDataProviderList(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "documentReference", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "includeQuerySpecification", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            boolean includeQuerySpecification)
            throws DSWSException_Exception
    ;

    /**
     * @param documentReference
     * @param session
     * @param dataProviderUID
     * @param includeQuerySpecification
     * @return returns com.ericsson.eniq.events.server.services.soap.queryservice.DataProviderInformation
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/getDataProviderInformation")
    @WebResult(name = "dataProviderInformation", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "getDataProviderInformation", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataProviderInformation")
    @ResponseWrapper(localName = "getDataProviderInformationResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.GetDataProviderInformationResponse")
    public DataProviderInformation getDataProviderInformation(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "documentReference", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "dataProviderUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataProviderUID,
            @WebParam(name = "includeQuerySpecification", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            boolean includeQuerySpecification)
            throws DSWSException_Exception
    ;

    /**
     * @param inputProperties
     * @param session
     * @param querySpecification
     * @param dataSourceUID
     * @param returnProperties
     * @return returns com.ericsson.eniq.events.server.services.soap.queryservice.DataProviderInformation
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/createDataProvider")
    @WebResult(name = "dataProviderInformation", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "createDataProvider", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.CreateDataProvider")
    @ResponseWrapper(localName = "createDataProviderResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.CreateDataProviderResponse")
    public DataProviderInformation createDataProvider(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "dataSourceUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataSourceUID,
            @WebParam(name = "querySpecification", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            QuerySpecification querySpecification,
            @WebParam(name = "returnProperties", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            ReturnProperties returnProperties,
            @WebParam(name = "inputProperties", targetNamespace = "http://queryservice.dsws.businessobjects.com/2007/06/01")
            InputProperties inputProperties)
            throws DSWSException_Exception
    ;

    /**
     * @param inputProperties
     * @param documentReference
     * @param session
     * @param querySpecification
     * @param dataProviderUID
     * @param dataSourceUID
     * @param returnProperties
     * @return returns com.ericsson.eniq.events.server.services.soap.queryservice.DataProviderInformation
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/modifyDataProvider")
    @WebResult(name = "dataProviderInformation", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "modifyDataProvider", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.ModifyDataProvider")
    @ResponseWrapper(localName = "modifyDataProviderResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.ModifyDataProviderResponse")
    public DataProviderInformation modifyDataProvider(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "documentReference", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "dataProviderUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataProviderUID,
            @WebParam(name = "dataSourceUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataSourceUID,
            @WebParam(name = "querySpecification", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            QuerySpecification querySpecification,
            @WebParam(name = "returnProperties", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            ReturnProperties returnProperties,
            @WebParam(name = "inputProperties", targetNamespace = "http://queryservice.dsws.businessobjects.com/2007/06/01")
            InputProperties inputProperties)
            throws DSWSException_Exception
    ;

    /**
     * @param documentReference
     * @param session
     * @param dataProviderUID
     * @return returns java.lang.String
     * @throws com.ericsson.eniq.events.server.services.soap.queryservice.DSWSException_Exception
     *
     */
    @WebMethod(action = "http://queryservice.dsws.businessobjects.com/2005/deleteDataProvider")
    @WebResult(name = "updatedDocumentReference", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
    @RequestWrapper(localName = "deleteDataProvider", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.DeleteDataProvider")
    @ResponseWrapper(localName = "deleteDataProviderResponse", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", className = "com.ericsson.eniq.events.server.services.soap.queryservice.DeleteDataProviderResponse")
    public String deleteDataProvider(
            @WebParam(name = "session", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String session,
            @WebParam(name = "documentReference", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String documentReference,
            @WebParam(name = "dataProviderUID", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005")
            String dataProviderUID)
            throws DSWSException_Exception
    ;

}
