package com.ericsson.eniq.events.server.services.soap.queryservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * Query Web Service
 * <p/>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "QueryService", targetNamespace = "http://queryservice.dsws.businessobjects.com/2005", wsdlLocation = "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/QueryService?wsdl")
public class QueryService_Service
        extends Service {

    private final static URL QUERYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(QueryService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = QueryService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/QueryService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/QueryService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYSERVICE_WSDL_LOCATION = url;
    }

    public QueryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryService_Service() {
        super(QUERYSERVICE_WSDL_LOCATION, new QName("http://queryservice.dsws.businessobjects.com/2005", "QueryService"));
    }

    /**
     * @return returns QueryService
     */
    @WebEndpoint(name = "QueryService")
    public QueryService getQueryService() {
        return super.getPort(new QName("http://queryservice.dsws.businessobjects.com/2005", "QueryService"), QueryService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns QueryService
     */
    @WebEndpoint(name = "QueryService")
    public QueryService getQueryService(WebServiceFeature... features) {
        return super.getPort(new QName("http://queryservice.dsws.businessobjects.com/2005", "QueryService"), QueryService.class, features);
    }

}
