package com.ericsson.eniq.events.server.services.soap.reports.bicatalog;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * BICatalog Web Service
 * <p/>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "BICatalog", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", wsdlLocation = "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/BICatalog?wsdl")
public class BICatalog
        extends Service {

    private final static URL BICATALOG_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ericsson.eniq.events.server.services.soap.reports.bicatalog.BICatalog.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ericsson.eniq.events.server.services.soap.reports.bicatalog.BICatalog.class.getResource(".");
            url = new URL(baseUrl, "http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/BICatalog?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://atrcxb1272vm1.athtem.eei.ericsson.se:8080/dswsbobje/services/BICatalog?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BICATALOG_WSDL_LOCATION = url;
    }

    public BICatalog(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BICatalog() {
        super(BICATALOG_WSDL_LOCATION, new QName("http://bicatalog.dsws.businessobjects.com/2007/06/01", "BICatalog"));
    }

    /**
     * @return returns BICatalogSoap
     */
    @WebEndpoint(name = "BICatalogSoap")
    public BICatalogSoap getBICatalogSoap() {
        return super.getPort(new QName("http://bicatalog.dsws.businessobjects.com/2007/06/01", "BICatalogSoap"), BICatalogSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BICatalogSoap
     */
    @WebEndpoint(name = "BICatalogSoap")
    public BICatalogSoap getBICatalogSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://bicatalog.dsws.businessobjects.com/2007/06/01", "BICatalogSoap"), BICatalogSoap.class, features);
    }

}
