package com.ericsson.eniq.events.server.services.soap.reports.bicatalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "BICatalogSoap", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BICatalogSoap {


    /**
     * Get all BI Catalog Objects for a folder or a category
     *
     * @param bicatalogObjectType
     * @param sort
     * @param session
     * @param objectPropertyNames
     * @param instanceRetrievalType
     * @param depth
     * @param resourceRightNames
     * @param objectUID
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.BICatalogObject>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getCatalog")
    @WebResult(name = "getCatalogResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getCatalog", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetCatalog")
    @ResponseWrapper(localName = "getCatalogResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetCatalogResponse")
    public List<BICatalogObject> getCatalog(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID,
            @WebParam(name = "depth", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            int depth,
            @WebParam(name = "sort", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<SortType> sort,
            @WebParam(name = "bicatalogObjectType", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> bicatalogObjectType,
            @WebParam(name = "resourceRightNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> resourceRightNames,
            @WebParam(name = "objectPropertyNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> objectPropertyNames,
            @WebParam(name = "instanceRetrievalType", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            InstanceRetrievalType instanceRetrievalType)
            throws DSWSException_Exception
    ;

    /**
     * Get Document list from a folder or a category
     *
     * @param session
     * @param objectUID
     * @param depth
     * @param sort
     * @param resourceRightNames
     * @param objectPropertyNames
     * @param instanceRetrievalType
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.Document>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getDocumentList")
    @WebResult(name = "getDocumentListResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getDocumentList", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetDocumentList")
    @ResponseWrapper(localName = "getDocumentListResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetDocumentListResponse")
    public List<Document> getDocumentList(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID,
            @WebParam(name = "depth", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            int depth,
            @WebParam(name = "sort", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<SortType> sort,
            @WebParam(name = "resourceRightNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> resourceRightNames,
            @WebParam(name = "objectPropertyNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> objectPropertyNames,
            @WebParam(name = "instanceRetrievalType", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            InstanceRetrievalType instanceRetrievalType)
            throws DSWSException_Exception
    ;

    /**
     * Get Category list from a folder or a category
     *
     * @param sort
     * @param session
     * @param objectPropertyNames
     * @param depth
     * @param resourceRightNames
     * @param objectUID
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.Category>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getCategoryList")
    @WebResult(name = "getCategoryListResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getCategoryList", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetCategoryList")
    @ResponseWrapper(localName = "getCategoryListResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetCategoryListResponse")
    public List<Category> getCategoryList(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID,
            @WebParam(name = "depth", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            int depth,
            @WebParam(name = "sort", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<SortType> sort,
            @WebParam(name = "resourceRightNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> resourceRightNames,
            @WebParam(name = "objectPropertyNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> objectPropertyNames)
            throws DSWSException_Exception
    ;

    /**
     * Get the Folder list from a folder or a category
     *
     * @param sort
     * @param session
     * @param objectPropertyNames
     * @param depth
     * @param resourceRightNames
     * @param objectUID
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.Folder>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getFolderList")
    @WebResult(name = "getFolderListResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getFolderList", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetFolderList")
    @ResponseWrapper(localName = "getFolderListResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetFolderListResponse")
    public List<Folder> getFolderList(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID,
            @WebParam(name = "depth", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            int depth,
            @WebParam(name = "sort", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<SortType> sort,
            @WebParam(name = "resourceRightNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> resourceRightNames,
            @WebParam(name = "objectPropertyNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> objectPropertyNames)
            throws DSWSException_Exception
    ;

    /**
     * Search a BI Catalog Objects
     *
     * @param sort
     * @param session
     * @param objectPropertyNames
     * @param searchPattern
     * @param instanceRetrievalType
     * @param resourceRightNames
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.BICatalogObject>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/searchDocument")
    @WebResult(name = "searchResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "search", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.SearchResponse")
    public List<BICatalogObject> search(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "searchPattern", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            SearchPattern searchPattern,
            @WebParam(name = "sort", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<SortType> sort,
            @WebParam(name = "resourceRightNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> resourceRightNames,
            @WebParam(name = "objectPropertyNames", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            List<String> objectPropertyNames,
            @WebParam(name = "instanceRetrievalType", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            InstanceRetrievalType instanceRetrievalType)
            throws DSWSException_Exception
    ;

    /**
     * Retrieve Resource Rights
     *
     * @param session
     * @param objectUID
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.ResourceRight>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getResourceRights")
    @WebResult(name = "getResourceRightsResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getResourceRights", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetResourceRights")
    @ResponseWrapper(localName = "getResourceRightsResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetResourceRightsResponse")
    public List<ResourceRight> getResourceRights(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID)
            throws DSWSException_Exception
    ;

    /**
     * Retrieve Object Properties
     *
     * @param session
     * @param objectUID
     * @return returns java.util.List<com.ericsson.eniq.events.server.services.soap.reports.bicatalog.ObjectProperty>
     * @throws DSWSException_Exception
     */
    @WebMethod(action = "http://bicatalog.dsws.businessobjects.com/2007/06/01/getObjectProperties")
    @WebResult(name = "getObjectPropertiesResult", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
    @RequestWrapper(localName = "getObjectProperties", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetObjectProperties")
    @ResponseWrapper(localName = "getObjectPropertiesResponse", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01", className = "com.ericsson.eniq.events.server.services.soap.reports.bicatalog.GetObjectPropertiesResponse")
    public List<ObjectProperty> getObjectProperties(
            @WebParam(name = "session", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String session,
            @WebParam(name = "objectUID", targetNamespace = "http://bicatalog.dsws.businessobjects.com/2007/06/01")
            String objectUID)
            throws DSWSException_Exception
    ;

}
